import scrapy
from datetime import datetime

class ModItem(scrapy.Item):
    id = scrapy.Field()
    name_en = scrapy.Field()
    name_zh = scrapy.Field()
    name_alias = scrapy.Field()
    description_en = scrapy.Field()
    description_zh = scrapy.Field()
    polarity = scrapy.Field()
    rarity = scrapy.Field()
    drain = scrapy.Field()
    max_rank = scrapy.Field()
    effect_en = scrapy.Field()
    effect_zh = scrapy.Field()
    image_url = scrapy.Field()
    wiki_url = scrapy.Field()
    last_updated = scrapy.Field()

class WeaponItem(scrapy.Item):
    id = scrapy.Field()
    name_en = scrapy.Field()
    name_zh = scrapy.Field()
    name_alias = scrapy.Field()
    description_en = scrapy.Field()
    description_zh = scrapy.Field()
    type = scrapy.Field()
    mastery_rank = scrapy.Field()
    damage = scrapy.Field()
    critical_chance = scrapy.Field()
    critical_multiplier = scrapy.Field()
    status_chance = scrapy.Field()
    image_url = scrapy.Field()
    wiki_url = scrapy.Field()
    last_updated = scrapy.Field()

class WarframeItem(scrapy.Item):
    id = scrapy.Field()
    name_en = scrapy.Field()
    name_zh = scrapy.Field()
    name_alias = scrapy.Field()
    description_en = scrapy.Field()
    description_zh = scrapy.Field()
    health = scrapy.Field()
    shield = scrapy.Field()
    armor = scrapy.Field()
    energy = scrapy.Field()
    sprint_speed = scrapy.Field()
    abilities_en = scrapy.Field()
    abilities_zh = scrapy.Field()
    passive_en = scrapy.Field()
    passive_zh = scrapy.Field()
    mastery_rank = scrapy.Field()
    polarities = scrapy.Field()
    image_url = scrapy.Field()
    wiki_url = scrapy.Field()
    last_updated = scrapy.Field() 